### ISSUE TITLE
BodyStyles sometimes crashes during SSR

### ISSUE THREAD

**Issue by hasparus** [system-ui/theme-ui#1178]
**Describe the bug**

`emotionTheme` seems to be undefined during Gatsby prerendering :thinking:
It's quite fun, because it doesn't happen consistently. 

```
TypeError: Cannot read property 'useBodyStyles' of undefined
    at styles (/home/hasparus/workspace/homepage/node_modules/@theme-ui/theme-provider/src/index.ts:18:15)
    at Object.children (/home/hasparus/workspace/homepage/node_modules/@emotion/core/dist/core.cjs.prod.js:79:50)
    at a.b.render (/home/hasparus/workspace/homepage/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:47:125)
    at a.b.read (/home/hasparus/workspace/homepage/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at Object.renderToStaticMarkup (/home/hasparus/workspace/homepage/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:462)
    at getSocialCardHtml (/home/hasparus/workspace/homepage/build-time/makeSocialCard/index.tsx:60:10)
    at Object.makeSocialCard (/home/hasparus/workspace/homepage/build-time/makeSocialCard/index.tsx:113:16)
    at createSocialImageNodeField (/home/hasparus/workspace/homepage/gatsby-node-ts.ts:429:27)
    at Object.exports.onCreateNode (/home/hasparus/workspace/homepage/gatsby-node-ts.ts:100:5)
```

**To Reproduce**

I'm not sure how to reproduce this TBH.
I'm just leaving it here to see if anybody has the same problem.

**Expected behavior**

Either early return in `BodyStyles > Global::styles` function or throw an error with meaningful message.

**Screenshots**

**Additional context**

I'm testing it on 0.4.0-rc.5, but it should also happen in 0.3.x looking at the old code for BodyStyles. 

I think errors on the boundary between Theme UI and Emotion happen quite often (e.g. context version mismatch), and I'm wondering what we could do with it.

**Comment by hasparus** [comment]
Workaround: I took the theme from `useThemeUI`.

```jsx
var BodyStyles = function BodyStyles() {
  const themeUI = core.useThemeUI() // <-- add this
  
  return core.jsx(core$1.Global, {
    styles: function styles(emotionTheme) {
      var theme = emotionTheme /* and this -> */ || themeUI.theme;

      if (theme.useBodyStyles === false || theme.styles && !theme.styles.root) {
        return false;
      }

      var boxSizing = theme.useBorderBox === false ? undefined : 'border-box';
      return css({
        '*': {
          boxSizing: boxSizing
        },
        body: {
          margin: 0,
          variant: 'styles.root'
        }
      })(theme);
    }
  });
};
```

**Comment by lachlanjc** [comment]
Have you seen this issue since? Worth keeping the issue open?
